### ISSUE TITLE
Some tables are not known to be scrollable on mobile

### ISSUE THREAD

**Issue by EKami** [kelyvin/caffeine-theme#27]
Hi @kelyvin ,
I'm reopening the previous issue #26, the tables on mobiles does not reveal to the user that they are scrollable.
For example with this table:
![screenshot_20161212-151219](https://cloud.githubusercontent.com/assets/4030626/21102321/01540916-c07e-11e6-9ed7-87e2a676e763.png)

You can't really know that there is a third column except if you magically scroll horizontally:
![screenshot_20161212-151236](https://cloud.githubusercontent.com/assets/4030626/21102371/3a8ce11c-c07e-11e6-9ba9-535839ac37e2.png)

Moreover the tables seems to be completely shrank on desktop:
<img width="1057" alt="activity_as_context__you_re_doing_it_wrong_" src="https://cloud.githubusercontent.com/assets/4030626/21104140/aa623e68-c085-11e6-8cad-2bb8770dde9a.png">

Thank you for your consideration 🙏

**Comment by kelyvin** [comment]
Shoot thanks for bringing this to my attention again! I'll need to implement this more thoroughly, I was testing this purely on my laptop screen so I wasn't able to test a proper mobile experience or on a large desktop screen. I'll have a fix for you asap!

**Comment by EKami** [comment]
Thanks a lot :)

**Comment by kelyvin** [comment]
Hi @EKami, 

I have enabled the scrollbar for mobile devices to always be visible. I've also fixed the border issue with the shrunken table. Those can be found in the following release: https://github.com/kelyvin/caffeine-theme/releases/tag/v2.8.2

Regarding the table shrinkage, unfortunately there's no easy way to manage the table width sizing across mobile/desktop devices and support responsiveness. Due to the fact that you can have `n` number of columns for a table, there's no "one size fits all" solution. 

For now this is the best I can do. If you'd like to incorporate a better responsive table solution, feel free to integrate a third party library and create a pull request, but for now this shoot be good for the majority of your use cases. :) 

Thanks!

**Comment by EKami** [comment]
Okay, thanks a lot for your consideration @kelyvin :)
