### ISSUE TITLE
I have found the solution to the block rendering problem

### ISSUE THREAD

**Issue by pupboss** [kelyvin/caffeine-theme#37]
The layout action would be executed after all resources finished, like this

```
$(window).load(function() {
  window.sr = window.ScrollReveal().reveal(cardName, {
      afterReveal: function () {
          if ($postsGrid) {
              $postsGrid.masonry("layout");
          }
      }
  });
});
```

So if there were any external resources can't be downloaded, the downloading would block the rendering.

My solution is `s.setAttribute('external_src', url)`

```
var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.setAttribute('external_src', '//' + window.disqus_shortname + '.disqus.com/count.js');
```

So that the `count.js` would not block the `load()` function.

After layout being executed, we can append a function like this

```
$(window).load(function() {
    $('[external_src]').each(function() {
        var external_src = $(this).attr("external_src");
        $(this).attr("src", $(this).attr("external_src")).removeAttr("external_src");
    });
});
```

**Comment by kelyvin** [comment]
Hm, I am not a fan of this potential solution as I'm not a fan of using javascript for script injections. 

I think there's a way we can use the capabilities of the browser to resolve the issue you're running into and prevent block rendering. I think all I need to do is simply add `async` to our external dependencies and that should resolve the issue. Since this theme also only supports IE10+ and evergreen browsers, this should resolve the issues. I'll do some more investigation and let you know what I find. 

Thanks for your patience @pupboss!
