### ISSUE TITLE
Adding Blog Description to Blog Header

### ISSUE THREAD

**Issue by ChristopherA** [kelyvin/caffeine-theme#40]
I have switched to caffiene-theme because the theme I was using before didn't have an active community. I appreciate that there seem to be more contributors here and more responsive to issues and pull requests.

In my old blog, the blog description (from settings general) were displayed below the blog title in the header. However, with cover set to be off in my blog, it doesn't show — only the title. Poking around (I'm not a web expert, more a coder) I can't seem to find the right place. Which file and what html should I add to my fork of the template to turn this on?

My blog is at http://www.livelywork.com/

**Comment by ChristopherA** [comment]
I have solved this for now by adding a blog.description to `aside.hbs`

```
<div class="blog-header">
    <a title="Link to homepage for {{@blog.title}}" href="{{@blog.url}}/#open">
        <h1 class="profile-title hvr-float">{{@blog.title}}</h1>
        <h2 class="profile-description">{{@blog.description}}</h2>
    </a>
    {{navigation}}
</div>
```

…and changing caffeine-theme.css to add an blog-header h2 style and modify h1

```
h1{color:#F6F4E9;margin:75px 0 10px;font-size:2.75rem}.blog-header h2{color:#F6F4E9;margin:0px 0 25px;font-size:2.00rem}.blog-header
```

However, I'm not closing this issue because:

1. The style should be added through SCSS build (but I don't have this toolchain set up).
2. I don't understand why this theme completely ignores the ghost native `@blog.description` and instead uses a header insert of `profile_resume`. I presume it is some interaction with the cover. But I think a feature supported by the general control panel should function in the theme.

**Comment by kelyvin** [comment]
HI @ChristopherA, 

Thanks for reaching out and for checking out the theme, I hope you're enjoying it so far!

The omittance of the `blog.description` from the header was an intentional design choice. This theme was designed with "mobile first" in mind. By adding the description to the header, when you open the blog from a mobile device, you'll see that you have less real estate to work with and wind up with the issue below:

![iphone_6_original](https://cloud.githubusercontent.com/assets/1530102/23934951/105a2adc-0906-11e7-904c-b791f2ec964f.png)

You can adjust by editing the text, making it smaller, moving the cards lower in the fold, and you may wind up with something like below.

![iphone_6_adjustments](https://cloud.githubusercontent.com/assets/1530102/23934953/14e88fee-0906-11e7-95a3-97a324dee2a6.png)

Sure this can work, but this is assuming that everyone's description is only several words long. The variability in this makes it hard to design and style. 

In addition, if you look at the UX side of things, wIth this change, your first card starts around the middle of your screen, and your first post title is already at the bottom of the screen (and potentially even cut off). The intention of a blog is to draw your audience into your first post, and the description at the top potentially distracts them. The header only contains the blog title & links to guide the user with navigation around the blog if needed. 

The best thing about open sourced code is that if you truly felt strongly about adding the description, you fork pull the code and you're more than welcome to make the changes yourself! Bonus points if you can also make it an "opt-in" feature that can be easily turned on/off through configuration, I would be more than happy to add it into the project. However, this is not something I will add by default.

**Comment by kelyvin** [comment]
I made the style changes by playing around in the Chrome developer tools for fast prototyping. 

You'll need to add a margin-top to the entire blog post container. So you can add a media query definition to `_media-queries.scss` with a class selector for `.page-index` and just add a `margin-top`.  For the description, in `_media-queries.scss`, add a style for `.blog-header` and add a different font size for that description.
