### ISSUE TITLE
Supporting Team Attribution

### ISSUE THREAD

**Issue by ChristopherA** [kelyvin/caffeine-theme#41]
Are there any plans for this theme to support the team / group blog features of Ghost, where different team members posts can be attributed, and link to author pages?

To see what I mean, see without author page http://www.livelywork.com/author/christophera/ vs with author page http://web.archive.org/web/20160422121954/http://www.livelywork.com/author/christophera/

**Comment by kelyvin** [comment]
That is a great question and this is definitely something I've been meaning to do, but hasn't been a priority of mine since I personally have been using this theme with one sole author (me). 

I'll mock up a design that fits the style of this theme and I'll see if I can whip something up in the next week or two for ya. Stay tuned!

**Comment by ChristopherA** [comment]
Thank you! I look forward to it.

**Comment by ChristopherA** [comment]
Any progress on this?

**Comment by kelyvin** [comment]
Hi @ChristopherA, 

Thanks for checking in. I have implemented this feature in the latest release here: https://github.com/kelyvin/caffeine-theme/releases/tag/v2.9.0. 

I'm still playing around the design for the `author credits` that's inserted at the end of every post, but I think this is a decent first attempt at it. Please check it and out and let me know if you run into issues or if you'd like to see more!
