### ISSUE TITLE
Search field not working

### ISSUE THREAD

**Issue by OaSiis** [kelyvin/caffeine-theme#47]
Hello,

I downloaded the caffeine-theme, installed it, added jQuery and other libraries.
Everything works fine except that the search field and popular tag are not working!
I get one error in the console: "Failed to load resource: the server responded with a status of 404 (Not Found)"  for the file /rss.

Can you help me please ?

**Comment by kelyvin** [comment]
HI @OaSiis, 

The search field uses an older version of a library called [ghostHunter](https://github.com/jamalneufeld/ghostHunter) to search within your blog. It performs searches against the RSS feed. If you are getting a 404 (Not Found) for the endpoint `/rss` of your blog. Can you confirm whether this endpoint returns an RSS feed (http://support.ghost.org/faq/find-rss-feed/)?

**Comment by OaSiis** [comment]
Hi @kelyvin ,

Thanks for your answer : myblog.com/rss returns a 404 page.

**Comment by kelyvin** [comment]
Since your blog is password protected, unfortunately I don't see any way around it given that this theme is currently using an older version of ghostHunter. 

The latest version of ghostHunter uses ghost's beta API instead for querying, which may not be constrained by password protection. However, I do not have plans on upgrading ghostHunter until the API until it is out of BETA (you have to opt into this feature within your settings at this moment).

**Comment by OaSiis** [comment]
Ok thanks for your help!
