### ISSUE TITLE
Is it compatible with Ghost v1.0.0?

### ISSUE THREAD

**Issue by roccomuso** [kelyvin/caffeine-theme#52]
Here the [migration guide](https://themes.ghost.org/docs/migrate-to-ghost-1-0-0).

**Comment by kelyvin** [comment]
Hi @roccomuso,

 I have not had the opportunity to test it yet, but I believe there is a couple of pull requests right now that should help address this. My plan is to take a look at all the requests this weekend as well as upgrade to 1.0 as well. 

Hope to support this new release very soon! Expect something by Monday. 

Thanks!

**Comment by pascalandy** [comment]
Just try it but there is few errors.

<img width="900" alt="screen shot 2017-08-12 at 11 02 16 am" src="https://user-images.githubusercontent.com/6694151/29241763-c5f897bc-7f4d-11e7-9833-ce962ca9ec38.png">

Cheers!

**Comment by kelyvin** [comment]
Good news! Thanks to everyone's help, I have updated the theme to support the latest version of Ghost! You can find that in the latest [v3.0.0 release](https://github.com/kelyvin/caffeine-theme/releases/tag/v3.0.0). 

Because this release was done to support the new Ghost v1.* update, please let me know if you run into any issues. Thanks for your patience and sorry for the delay!
