### ISSUE TITLE
Add social_links and no icon shown

### ISSUE THREAD

**Issue by Dedsic** [kelyvin/caffeine-theme#60]
For example I add a commet link like this
```
    <!-- Comments-->
    <li class="social item hvr-grow-rotate">
        <a rel="me" target="_blank" href="http://blablabla" title="chat with us">
            <i class="fas fa-comments"></i>
            <span class="label">comments</span>
        </a>
    </li>
```
And I don't get any icon shown. Any way to solve that ?
Thank you for coding and watching this issue.

**Comment by kelyvin** [comment]
Hi @Dedsic, 

You may have a typo for the following line: 

` <i class="fas fa-comments"></i>`

Can you remove the `s` within `fas`. So it should look like:

` <i class="fa fa-comments"></i>`

This project still uses font-awesome icon pack 4, I believe font-awesome has upgraded to 5 recently which is why you have the `fas`. I'll put in a ticket for me to update that soon. Let me know if that fixes your issue in the meantime!

**Comment by kelyvin** [comment]
Going to close this issue, feel free to reopen if you still run into any problems!
